name: deploy
on: [push]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
#          port: ${{ secrets.PORT }}
          script: |
            mkdir deploy_dist
            cd deploy_dist
            touch deploy.txt
            echo "hello deploy" >> deploy.txt
            cat deploy.txt
